# This file was generated by GoReleaser. DO NOT EDIT.
cask "kasmos" do
  name "kasmos"
  desc "kas - A TUI-based agent-driven IDE for managing multiple AI agents"
  homepage "https://github.com/kastheco/kasmos"
  version "1.3.14"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kasmos"

  on_macos do
    on_intel do
      url "https://github.com/kastheco/kasmos/releases/download/v#{version}/kasmos_#{version}_darwin_amd64.tar.gz"
      sha256 "02a7efe65b7932aebaa2151c70e364719281788ea7cdca3484f9caa1b8d1b534"
    end
    on_arm do
      url "https://github.com/kastheco/kasmos/releases/download/v#{version}/kasmos_#{version}_darwin_arm64.tar.gz"
      sha256 "97796cf7357e73b8078fb6a8a5e021164d971efecbe68e9b2fb134bca0310234"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kastheco/kasmos/releases/download/v#{version}/kasmos_#{version}_linux_amd64.tar.gz"
      sha256 "84124e9812b061428c7d28e477828dbc2df1882f0a406acf385fcc40e2f65a38"
    end
    on_arm do
      url "https://github.com/kastheco/kasmos/releases/download/v#{version}/kasmos_#{version}_linux_arm64.tar.gz"
      sha256 "93bf5247cad061b99d6b884c2732e9414f318abc5a9cdc25a337ae942781ac4c"
    end
  end

  # No zap stanza required
end
