# This file was generated by GoReleaser. DO NOT EDIT.
cask "kasmos" do
  name "kasmos"
  desc "kas - A TUI-based agent-driven IDE for managing multiple AI agents"
  homepage "https://github.com/kastheco/kasmos"
  version "2.0.0-beta-4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kasmos"

  on_macos do
    on_intel do
      url "https://github.com/kastheco/kasmos/releases/download/v#{version}/kasmos_#{version}_darwin_amd64.tar.gz"
      sha256 "2360e54b27a16e2f3cc432ae794a494e95ee871bf8efa05d7ec166abad4b19b8"
    end
    on_arm do
      url "https://github.com/kastheco/kasmos/releases/download/v#{version}/kasmos_#{version}_darwin_arm64.tar.gz"
      sha256 "e1b5197a05f28e977a05a70a4b5f22edf7147bd9a475c604c90754abcabe3f56"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kastheco/kasmos/releases/download/v#{version}/kasmos_#{version}_linux_amd64.tar.gz"
      sha256 "694aa00a0fa71fc80df851601c89a5e152bd49b70bc6d6df4af5a621cb72de28"
    end
    on_arm do
      url "https://github.com/kastheco/kasmos/releases/download/v#{version}/kasmos_#{version}_linux_arm64.tar.gz"
      sha256 "b638349116f93b15a11cb3cfa50f4480e83344369d20c17d354b1c0a243e7752"
    end
  end

  # No zap stanza required
end
